trigger: none

resources:
  repositories:
  - repository: release
    type: git
    name: Samsung/ReleaseVersion
    trigger: none
    ref: refs/heads/main
  - repository: helm
    type: git
    name: Samsung/helms
    trigger: none
    ref: refs/heads/main

variables:
  customer: 'busby'
  environment: 'prod'
  region: 'uks'
  namespace: 'shared'
  serviceConnectionName: 'glow-busby-subs'
  kubernetesClusterResourceGroup: "rg-prod-uks-busby"
  kubernetesClusterName: "prod-uks-busby"
  chartPath: "helms/helms/shared"

name: deploy-shared-services-PROD-uks-busby-$(date:yyyyMMdd)-buildID-$(Build.BuildId)

pool:
  name: GlowProdPool

stages:  
- stage: Deploy_release
  jobs:
  - deployment: Deploy
    environment: 'EE_UKS_PROD_GLOW'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - checkout: release
          - checkout: helm

          - task: AzureKeyVault@2
            displayName: 'Export Azure Key Vault secrets from kv-$(environment)-$(region)-$(customer)'
            inputs:
              azureSubscription: $(serviceConnectionName)
              KeyVaultName: kv-$(environment)-$(region)-$(customer)
              RunAsPreJob: true

          - task: AzureCLI@2
            displayName: 'Set commitHash'
            inputs:
              azureSubscription: $(serviceConnectionName)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                cd helms
                commitHash=$(git rev-parse --short HEAD)
                echo "##vso[task.setvariable variable=commitHash]$commitHash"
                echo "$commitHash"

          - task: KubectlInstaller@0
            displayName: 'Install Kubectl 1.27.3'
            inputs: 
              kubectlVersion: 1.27.3 

          - task: HelmInstaller@1
            displayName: 'Install Helm 3.10.0'
            inputs:
              helmVersionToInstall: 3.10.0
              
          - template: templates/ps.set_images.yml
            parameters:
              customer: "$(customer)"
              environment: "$(environment)"
              region: "$(region)"
              namespace: "$(namespace)"

          - template: templates/task.map_kv_helm.yml
            parameters:
              serviceConnectionName: "$(serviceConnectionName)"

          # pdfgen-gotenberg
          - template: templates/application.yml
            parameters:
              serviceName: "pdfgen-gotenberg"
              imageRepository: "$(imageRepository)/pdfgen-gotenberg"
              imageTag: "$(pdfgen-gotenbergCI)"
              chartPath: "$(chartPath)"
              serviceConnectionName: "$(serviceConnectionName)"
              kubernetesClusterResourceGroup: "$(kubernetesClusterResourceGroup)"
              kubernetesClusterName: "$(kubernetesClusterName)"
              namespace: "$(namespace)"
              commitHash: "$(commitHash)"
              TempVars: "$(TempVars)"

          # pdfgen-wkhtmltopdf
          - template: templates/application.yml
            parameters:
              serviceName: "pdfgen-wkhtmltopdf"
              imageRepository: "$(imageRepository)/pdfgen-wkhtmltopdf"
              imageTag: "$(pdfgen-wkhtmltopdfCI)"
              chartPath: "$(chartPath)"
              serviceConnectionName: "$(serviceConnectionName)"
              kubernetesClusterResourceGroup: "$(kubernetesClusterResourceGroup)"
              kubernetesClusterName: "$(kubernetesClusterName)"
              namespace: "$(namespace)"
              commitHash: "$(commitHash)"
              TempVars: "$(TempVars)"